# Docker Compose for local development with app included
services:
  postgres:
    image: postgres:16-alpine
    container_name: people-finder-dev-postgres
    environment:
      POSTGRES_DB: peoplefinder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - people-finder
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: people-finder-dev-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9010:9000"
      - "9011:9001"
    volumes:
      - minio_data:/data
    networks:
      - people-finder
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  app:
    image: node:20-alpine
    container_name: people-finder-dev-app
    working_dir: /app
    env_file:
      - .env
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/peoplefinder?schema=public
      MINIO_ENDPOINT: minio
      MINIO_PORT: "9000"
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET_NAME: people-finder
      MINIO_USE_SSL: "false"
    ports:
      - "3010:3000"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - people-finder
    restart: unless-stopped
    volumes:
      # Mount entire project for development
      - .:/app
      - /app/node_modules
      - /app/.next
    command: sh -c "npm install && npm run dev"

volumes:
  postgres_data:
    name: people_finder_dev_postgres
  minio_data:
    name: people_finder_dev_minio

networks:
  people-finder:
    name: people-finder-dev
    driver: bridge