# Default docker-compose for local development
# For production deployment, use: docker-compose.cloudflare.yml

services:
  postgres:
    image: postgres:16-alpine
    container_name: people-finder-dev-postgres
    environment:
      POSTGRES_DB: people_finder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devpassword123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - people-finder
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: people-finder-dev-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: devpassword123
    ports:
      - "9010:9000"
      - "9011:9001"
    volumes:
      - minio_data:/data
    networks:
      - people-finder
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: people-finder-dev-opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - DISABLE_SECURITY_PLUGIN=true
      - DISABLE_INSTALL_DEMO_CONFIG=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - people-finder
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.0
    container_name: people-finder-dev-opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    ports:
      - "5601:5601"
    networks:
      - people-finder
    depends_on:
      opensearch:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
    name: people_finder_dev_postgres
  minio_data:
    name: people_finder_dev_minio
  opensearch_data:
    name: people_finder_dev_opensearch

networks:
  people-finder:
    name: people-finder-dev
    driver: bridge