name: Deploy to Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggers

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /opt/people-finder
          
          # Pull latest changes
          git pull origin main
          
          # Deploy with the Cloudflare script
          chmod +x deploy-cloudflare.sh
          ./deploy-cloudflare.sh
          
          # Check if deployment was successful
          sleep 10
          if curl -f http://localhost:3020/api/health; then
            echo "✅ Deployment successful!"
          else
            echo "❌ Deployment failed - check logs"
            docker-compose -f docker-compose.cloudflare.yml logs --tail=50
            exit 1
          fi